from __future__ import annotations
from pathlib import Path
from jinja2 import Environment, BaseLoader
from python.risk_matrix import RiskRegister, get_color

_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Risk Assessment — {{ register.organization }}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Segoe UI',system-ui,sans-serif;background:#f8fafc;color:#1e293b;line-height:1.6}
.page{max-width:1100px;margin:0 auto;padding:2rem}
header{background:#0f172a;color:#f1f5f9;padding:2rem;border-radius:12px;margin-bottom:2rem}
header h1{font-size:1.5rem;font-weight:800}
.meta{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:1rem;margin-top:1rem}
.meta dt{font-size:.65rem;text-transform:uppercase;letter-spacing:.08em;color:#64748b}
.meta dd{font-size:.9rem;font-weight:600;color:#e2e8f0}
.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:1rem;margin-bottom:2rem}
.sum-card{background:#fff;border-radius:10px;padding:1.25rem;text-align:center;border-top:4px solid}
.sum-card .n{font-size:2.5rem;font-weight:800;line-height:1}
.sum-card .l{font-size:.65rem;text-transform:uppercase;letter-spacing:.08em;color:#64748b;margin-top:.2rem}
h2{font-size:.75rem;text-transform:uppercase;letter-spacing:.08em;color:#64748b;margin:2rem 0 1rem}
table{width:100%;border-collapse:collapse;font-size:.85rem;background:#fff;border-radius:10px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.05)}
th{text-align:left;padding:.6rem 1rem;font-size:.65rem;text-transform:uppercase;letter-spacing:.06em;color:#64748b;background:#f8fafc;border-bottom:2px solid #e2e8f0}
td{padding:.8rem 1rem;border-bottom:1px solid #f1f5f9;vertical-align:top}
tr:hover td{background:#fafafa}
.badge{display:inline-block;padding:.2rem .65rem;border-radius:999px;font-size:.65rem;font-weight:700;color:#fff}
footer{text-align:center;font-size:.75rem;color:#94a3b8;margin-top:3rem;padding-top:1.5rem;border-top:1px solid #e2e8f0}
</style>
</head>
<body>
<div class="page">
  <header>
    <h1>Risk Assessment Matrix — {{ register.organization }}</h1>
    <dl class="meta">
      <div><dt>Assessor</dt><dd>{{ register.assessor }}</dd></div>
      <div><dt>Date</dt><dd>{{ register.assessment_date }}</dd></div>
      <div><dt>Total Risks</dt><dd>{{ register.risks | length }}</dd></div>
    </dl>
  </header>

  <h2>Summary</h2>
  <div class="summary">
    {% for level, color in [('critical','#dc2626'),('high','#f97316'),('medium','#eab308'),('low','#22c55e')] %}
    <div class="sum-card" style="border-top-color:{{ color }}">
      <div class="n" style="color:{{ color }}">{{ summary[level] }}</div>
      <div class="l">{{ level }}</div>
    </div>
    {% endfor %}
  </div>

  <h2>Risk Register (sorted by score)</h2>
  <table>
    <thead>
      <tr>
        <th>ID</th><th>Risk</th><th>Category</th>
        <th>L</th><th>I</th><th>Score</th>
        <th>Owner</th><th>Due Date</th><th>Status</th><th>Mitigation</th>
      </tr>
    </thead>
    <tbody>
    {% for r in risks %}
      <tr>
        <td style="font-family:monospace;font-size:.75rem;color:#94a3b8">{{ r.id }}</td>
        <td>
          <strong>{{ r.title }}</strong>
          {% if r.description %}<div style="font-size:.78rem;color:#64748b;margin-top:.2rem">{{ r.description }}</div>{% endif %}
        </td>
        <td style="font-size:.78rem">{{ r.category }}</td>
        <td style="text-align:center">{{ r.likelihood }}</td>
        <td style="text-align:center">{{ r.impact }}</td>
        <td style="text-align:center">
          <span class="badge" style="background:{{ r.color }}">{{ r.score }}</span>
        </td>
        <td style="font-size:.78rem">{{ r.owner or '—' }}</td>
        <td style="font-size:.75rem;color:#94a3b8">{{ r.due_date or '—' }}</td>
        <td><span style="font-size:.75rem">{{ r.status }}</span></td>
        <td style="font-size:.78rem;color:#475569">{{ r.mitigation or '—' }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <footer>Generated by risk-assessment-matrix &mdash; {{ register.assessment_date }}</footer>
</div>
</body>
</html>
"""


def generate_html_report(register: RiskRegister, output_path: str) -> None:
    env = Environment(loader=BaseLoader(), autoescape=True)
    template = env.from_string(_TEMPLATE)
    html = template.render(
        register=register,
        risks=register.sorted_risks(),
        summary=register.summary(),
    )
    Path(output_path).write_text(html, encoding="utf-8")
    print(f"[+] Report written to {output_path}")
